'use client';

import React from 'react';
import Link from 'next/link';
import { ArrowLeft, ShieldAlert } from 'lucide-react';
import Card from '@/components/ui/Card';
import FadeIn from '@/components/animations/FadeIn';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#090B0F] text-[#F8FAFC] py-20 px-6">
      <div className="max-w-3xl mx-auto flex flex-col gap-8">
        
        <Link href="/" className="inline-flex items-center gap-2 text-sm text-[#A8B3C7] hover:text-[#D4AF37] transition-colors self-start">
          <ArrowLeft className="w-4 h-4" /> Back to Dashboard
        </Link>

        <FadeIn direction="up">
          <div className="flex flex-col gap-4">
            <h1 className="text-3xl md:text-4xl font-black tracking-tight text-[#F8FAFC]">Terms of Service</h1>
            <p className="text-[#A8B3C7] text-sm">Last Updated: {new Date().toLocaleDateString()}</p>
          </div>
        </FadeIn>

        <FadeIn direction="up" delay={0.1}>
          <Card className="p-6 md:p-10 border-[rgba(255,255,255,0.06)] bg-[#11151C] flex flex-col gap-8" padding="none">
            
            <div className="p-4 bg-[rgba(212,175,55,0.05)] border border-[rgba(212,175,55,0.15)] rounded-xl flex items-start gap-3">
              <ShieldAlert className="w-5 h-5 text-[#D4AF37] shrink-0 mt-0.5" />
              <div className="flex flex-col gap-1">
                <h3 className="text-sm font-bold text-[#F8FAFC]">Not Legal Advice</h3>
                <p className="text-xs text-[#A8B3C7] leading-relaxed">
                  LexAI is an AI-powered legal analysis tool designed to assist with contract review. <strong>It does not constitute professional legal advice, nor does it create an attorney-client relationship.</strong> Always consult a qualified attorney in your jurisdiction for any definitive legal matters or before executing any legal agreement.
                </p>
              </div>
            </div>

            <section className="flex flex-col gap-3">
              <h2 className="text-lg font-bold text-[#F8FAFC]">1. Acceptance of Terms</h2>
              <p className="text-sm text-[#A8B3C7] leading-relaxed">
                By accessing or using LexAI ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Platform. The Platform is provided strictly "as is" and "as available".
              </p>
            </section>

            <section className="flex flex-col gap-3">
              <h2 className="text-lg font-bold text-[#F8FAFC]">2. Data Privacy & Stateless Architecture</h2>
              <p className="text-sm text-[#A8B3C7] leading-relaxed">
                LexAI operates on a strict Zero Data Retention policy. We do not store your uploaded documents, contracts, or generated analysis on our servers. All document processing is transient, and reports are saved exclusively in your browser's local memory (`sessionStorage`). Once you close your browser tab or session, the data is permanently erased. You are solely responsible for saving or exporting any analysis you wish to keep.
              </p>
            </section>

            <section className="flex flex-col gap-3">
              <h2 className="text-lg font-bold text-[#F8FAFC]">3. AI Accuracy & Limitations</h2>
              <p className="text-sm text-[#A8B3C7] leading-relaxed">
                The analysis, risk scoring, and clause summaries are generated by Artificial Intelligence (Large Language Models). While we strive for high accuracy, AI models can hallucinate, omit critical context, or misinterpret complex legal language. You agree that LexAI and its developers are not liable for any damages, losses, or legal complications arising from reliance on the AI-generated outputs.
              </p>
            </section>

            <section className="flex flex-col gap-3">
              <h2 className="text-lg font-bold text-[#F8FAFC]">4. Prohibited Uses</h2>
              <p className="text-sm text-[#A8B3C7] leading-relaxed">
                You agree not to use the Platform to:
              </p>
              <ul className="list-disc list-inside text-sm text-[#A8B3C7] leading-relaxed flex flex-col gap-1 ml-2">
                <li>Upload documents containing illicit, illegal, or highly classified government information.</li>
                <li>Attempt to reverse-engineer, exploit, or perform denial-of-service (DoS) attacks against our infrastructure.</li>
                <li>Use the platform's outputs to impersonate a licensed legal professional.</li>
              </ul>
            </section>

            <section className="flex flex-col gap-3">
              <h2 className="text-lg font-bold text-[#F8FAFC]">5. Governing Law</h2>
              <p className="text-sm text-[#A8B3C7] leading-relaxed">
                These terms shall be governed by and construed in accordance with the laws of the applicable jurisdiction, without regard to its conflict of law provisions. Any disputes arising from the use of LexAI shall be subject to the exclusive jurisdiction of the competent courts.
              </p>
            </section>

          </Card>
        </FadeIn>
      </div>
    </div>
  );
}
