import { NextRequest, NextResponse } from 'next/server';
import { jsPDF } from 'jspdf';

export async function POST(req: NextRequest) {
  try {
    const data = await req.json();
    const { document, analysis, clauses } = data;

    if (!document || !analysis) {
      return NextResponse.json({ error: 'Missing document or analysis data' }, { status: 400 });
    }

    const doc = new jsPDF();
    const docWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = docWidth - 2 * margin;
    let y = 20;

    // Helper: text wrapping and adding
    const addWrappedText = (text: string, fontSize: number, color: [number, number, number], fontStyle = 'normal') => {
      doc.setFont('helvetica', fontStyle);
      doc.setFontSize(fontSize);
      doc.setTextColor(color[0], color[1], color[2]);
      
      const lines = doc.splitTextToSize(text || '', contentWidth);
      for (const line of lines) {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        doc.text(line, margin, y);
        y += fontSize * 0.45;
      }
      y += 3; // spacing
    };

    // Header Glow Banner
    doc.setFillColor(10, 10, 26); // #0a0a1a deep dark navy background
    doc.rect(0, 0, docWidth, 40, 'F');
    
    // Header Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(99, 102, 241); // indigo-500
    doc.text('LexAI Legal Report', margin, 25);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text('AI-POWERED CONTRACT RISK ANALYSIS', margin, 32);
    
    y = 50;

    // Document Info
    doc.setFillColor(241, 245, 249); // light grey block for metadata
    doc.rect(margin, y, contentWidth, 25, 'F');
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42); // slate-900
    doc.text(`Document Name: ${document.fileName || 'Contract.pdf'}`, margin + 5, y + 8);
    
    const docTypeLabel = (document.docType || 'agreement').replace(/_/g, ' ').toUpperCase();
    doc.text(`Detected Type: ${docTypeLabel}`, margin + 5, y + 15);
    doc.text(`Risk Score: ${analysis.overallScore || 0}/100`, margin + 110, y + 15);
    
    y += 35;

    // Executive Summary
    addWrappedText('Executive Summary', 14, [99, 102, 241], 'bold');
    addWrappedText(analysis.summary || 'No summary available.', 10, [51, 65, 85]);
    y += 5;

    // Top 3 Things to Know
    if (analysis.topThingsToKnow && analysis.topThingsToKnow.length > 0) {
      addWrappedText('Top Things to Know Before Signing', 14, [99, 102, 241], 'bold');
      analysis.topThingsToKnow.forEach((item: string, idx: number) => {
        addWrappedText(`${idx + 1}. ${item}`, 10, [15, 23, 42]);
      });
      y += 5;
    }

    // Riskiest Clauses
    const riskyClauses = (clauses || [])
      .filter((c: any) => c.riskLevel === 'high' || c.riskLevel === 'critical')
      .slice(0, 5);

    if (riskyClauses.length > 0) {
      addWrappedText('Critical Risk Clauses Detected', 14, [239, 68, 68], 'bold'); // Red
      
      riskyClauses.forEach((c: any, idx: number) => {
        addWrappedText(`${idx + 1}. [${c.category || 'Clause'}] (Risk Score: ${c.riskScore}/100 - ${c.riskLevel.toUpperCase()})`, 11, [15, 23, 42], 'bold');
        addWrappedText(`Original Clause: "${c.text.trim().substring(0, 250)}..."`, 9, [100, 116, 139], 'italic');
        addWrappedText(`Explanation: ${c.explanation || 'N/A'}`, 9.5, [51, 65, 85]);
        addWrappedText(`Suggested Counter-Clause: ${c.counterClause || 'N/A'}`, 9.5, [16, 185, 129], 'bold'); // Green
        y += 4;
      });
    }

    // Negotiation Guide
    if (analysis.negotiationGuide) {
      const guide = analysis.negotiationGuide;
      
      if (guide.dos && guide.dos.length > 0) {
        addWrappedText('Negotiation Recommendations (Dos)', 14, [16, 185, 129], 'bold');
        guide.dos.forEach((item: string) => {
          addWrappedText(`[✓] ${item}`, 10, [51, 65, 85]);
        });
        y += 5;
      }
      
      if (guide.donts && guide.donts.length > 0) {
        addWrappedText('Negotiation Warnings (Don\'ts)', 14, [239, 68, 68], 'bold');
        guide.donts.forEach((item: string) => {
          addWrappedText(`[✗] ${item}`, 10, [51, 65, 85]);
        });
        y += 5;
      }
    }

    // Footer info
    const pageCount = doc.internal.pages.length - 1;
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Page ${i} of ${pageCount}`, docWidth - 30, 287);
      doc.text('Confidential - Generated by LexAI', margin, 287);
    }

    const pdfBuffer = doc.output('arraybuffer');

    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="LexAI_Report_${document.id}.pdf"`,
      },
    });

  } catch (error: any) {
    return NextResponse.json({ error: error?.message || 'Failed to generate PDF' }, { status: 500 });
  }
}
